### ISSUE TITLE
ASK: where is cache save?

### ISSUE THREAD

**Issue by ryuxname** [epicweb-dev/cachified#112]

**Comment by kentcdodds** [comment]
I don't understand the question.

**Comment by ryuxname** [comment]
Sorry, but by default, is the cache stored on the server or in the browser?

**Comment by kentcdodds** [comment]
There is no default. You provide a cache implementation. It depends on that implementation.

**Comment by ryuxname** [comment]
sorry sir, but i want to know where my cache is stored. i didn't do any settings, just followed the documentation

**Comment by kentcdodds** [comment]
If you're following the first example from the README and using lru-cache then your cache is stored in memory as lru-cache is an in-memory cache.

But you can use a number of different caching implementations or implement your own that store the value anywhere you like.
