### ISSUE TITLE
Adding a reporter changes return type of `getFreshValue` to `unknown`

### ISSUE THREAD

**Issue by maxfi** [epicweb-dev/cachified#70]
Without the reporter:

```ts
import { LRUCache } from "lru-cache";
import { cachified, CacheEntry } from "cachified";

const lru = new LRUCache<string, CacheEntry>({ max: 1000 });

function getUser() {
  return cachified({
    key: `user`,
    cache: lru,
    async getFreshValue() {
           //    ^? (property) CachifiedOptions<{ name: string; }>.getFreshValue: GetFreshValue<{ name: string }>
      return { name: 'Max' }
    },
  });
}
```

With the reporter:

```ts
import { LRUCache } from "lru-cache";
import { cachified, CacheEntry, verboseReporter } from "cachified";

const lru = new LRUCache<string, CacheEntry>({ max: 1000 });

function getUser() {
  return cachified({
    key: `user`,
    cache: lru,
    reporter: verboseReporter(),
    async getFreshValue() {
           //    ^? (property) CachifiedOptions<unknown>.getFreshValue: GetFreshValue<unknown>
      return { name: 'Max' }
    },
  });
}
```

Reproduction: [Typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgGQEoFUDCBDAxgCwFM4BfOAMyghDgCIAbKAVwFpc8jaBuAWAChQkWIjjsCwcsEIATADRwcBQgFEAdjCgBPeQDdCUAEYQAzoVSEhMfaQpUatMfglTp3fv1wRVx+IyZwAXjhVQgB3FAxFIgAeHyhgVQBzeSiVdS0APgAKJBBsAA8ALjgARgAGCtIASl4+fnImVVwYYC84RMIYdFMoLKrEfjg4KE6mKFVRDmcZHMGh4YtoKyhivUMTM0XYfT7ZOaHHQmK-Pb55uABrQk1igAMmHtvT8+xjTSb2zoAxEeN8ADVsPQmIQ+gMzudIXAAPTQ84APQA-Pt5iMYGMJkhVNgQEc4AByACyBXxpBRJGe1VqJH4QA)

Is this possibly related to https://github.com/Xiphe/cachified/issues/5?

**Comment by Xiphe** [comment]
That's a really interesting edge-case! Thanks for reporting.

Upon debugging I found that the following works:

```ts
import { LRUCache } from "lru-cache";
import { cachified, CacheEntry, verboseReporter } from "cachified";

const lru = new LRUCache<string, CacheEntry>({ max: 1000 });

function getUser() {
  return cachified({
    key: `user`,
    cache: lru,
    reporter: verboseReporter(),
   getFreshValue: async () => {
      //          👆 use arrow function here 
      return { name: 'Max' }
    },
  });
}
```

But that doesn't seem like a sustainable solution to me :)

Another solution would be to explicitly type the call like this:

```ts
import { LRUCache } from "lru-cache";
import { cachified, CacheEntry, verboseReporter } from "cachified";

const lru = new LRUCache<string, CacheEntry>({ max: 1000 });

function getUser() {
  return cachified<{ name: string }>({
    //             👆 add type explicitly here
    key: `user`,
    cache: lru,
    reporter: verboseReporter(),
    async getFreshValue() {
      return { name: 'Max' }
    },
  });
}
```

But that's also something that I would expect TS to handle magically....

---

Unfortunately I don't have a simple non-breaking solution this this currently. I tend to think that it wouldn't hurt to make the reporter work on an un-inferred `unknown` similar to how the cache works but that would be a breaking change to the API.

Would be interested in different solutions to this 🙏

**Comment by kentcdodds** [comment]
I'm afraid I haven't taken the time to understand the situation here, but if anyone is interested in making a pull request to fix this we're going to be making a breaking change here soon so now would be a good time to have this ready to go.

**Comment by Xiphe** [comment]
Good point! Will have another look at this today or tomorrow.
