### ISSUE TITLE
move into epicweb-dev?

### ISSUE THREAD

**Issue by Xiphe** [epicweb-dev/cachified#74]
Hi @kentcdodds,

Long term I'm looking to step down from maintaining open source projects for various personal reaons.

So I wanted to ask what you think about moving this into the @epicweb-dev org? 

For now I'd happily continue maintaining this in either space but I'd appreciate if there would be some more potential maintainers.

**Comment by kentcdodds** [comment]
I completely understand and I'll be happy to move it into the epic web org and publish it under the epic web npm namespace as well. If that sounds ok to you then I'll get things ready to go for that transition.

**Comment by Xiphe** [comment]
sounds great! Let's do this 👍

**Comment by kentcdodds** [comment]
Could you give me admin rights so I can transfer this into the Epic Web org and update the actions?

**Comment by Xiphe** [comment]
Wasn't able to grand you admin rights while this was on my personal account. Also wasn't able to move it into @epicweb-dev because I'm not allowed to create public repos in there. Therefore moved into @kalispera for now and you have admin rights now. 
Let me know if this works :)

**Comment by Xiphe** [comment]
Done! Thanks a lot for the help with this 👍

**Comment by kentcdodds** [comment]
Thanks!

I just checked https://npm.im/cachified and I see v4 was published, but it doesn't look like it was deprecated. Did you run that command?

**Comment by Xiphe** [comment]
Ah, seems as if that hasn't run through correctly. Thanks for double-checking 🙏 It's done now

<img width="1238" alt="image" src="https://github.com/epicweb-dev/cachified/assets/911218/2c7aa34a-8d44-4407-a499-0fc3cb217fec">

**Comment by kentcdodds** [comment]
Thanks! That went well 👍
